package main

var defaultHttpEndpoints = map[string]HttpEndpoint{
	"videoStream":              HttpEndpoint{Response: "videoStream"},
	"rawVideoStream":           HttpEndpoint{Response: "rawVideoStream"},
	"audioStream":              HttpEndpoint{Response: "audioStream"},
	"rawAudioStream":           HttpEndpoint{Response: "rawAudioStream"},
	"clipboardStream":          HttpEndpoint{Response: "clipboardStream"},
	"uhidOutputStream":         HttpEndpoint{Response: "uhidOutputStream"},
	"clipboard":                HttpEndpoint{Response: "clipboard", ClipboardTimeout: 1000},
	"clipboardCut":             HttpEndpoint{Response: "clipboard", ClipboardCut: true, ClipboardTimeout: 1000},
	"deviceName":               HttpEndpoint{Response: "deviceName"},
	"videoCodec":               HttpEndpoint{Response: "videoCodec"},
	"audioCodec":               HttpEndpoint{Response: "audioCodec"},
	"initialVideoWidth":        HttpEndpoint{Response: "initialVideoWidth"},
	"initialVideoHeight":       HttpEndpoint{Response: "initialVideoHeight"},
	"videoFrame":               HttpEndpoint{Response: "videoFrame"},
	"encoders":                 HttpEndpoint{Response: "encoders"},
	"displays":                 HttpEndpoint{Response: "displays"},
	"cameras":                  HttpEndpoint{Response: "cameras"},
	"apps":                     HttpEndpoint{Response: "apps"},
	"cameraSizes":              HttpEndpoint{Response: "cameraSizes"},
	"connect":                  HttpEndpoint{Commands: [][]string{{"connect"}}},
	"disconnect":               HttpEndpoint{Commands: [][]string{{"disconnect"}}},
	"startscrcpyserver":        HttpEndpoint{Commands: [][]string{{"startscrcpyserver"}}},
	"stopscrcpyserver":         HttpEndpoint{Commands: [][]string{{"stopscrcpyserver"}}},
	"uhidinput":                HttpEndpoint{Commands: [][]string{{"uhidinput", "$id", "$data"}}},
	"key":                      HttpEndpoint{Commands: [][]string{{"key", "$key"}}},
	"key2":                     HttpEndpoint{Commands: [][]string{{"key2", "$keycode"}}},
	"key3":                     HttpEndpoint{Commands: [][]string{{"key3", "$key", "$up", "$repeat", "$metastate"}}},
	"key4":                     HttpEndpoint{Commands: [][]string{{"key4", "$keycode", "$up", "$repeat", "$metastate"}}},
	"type":                     HttpEndpoint{Commands: [][]string{{"type", "$text"}}},
	"touch":                    HttpEndpoint{Commands: [][]string{{"touch", "$x", "$y", "$w", "$h"}}},
	"touchdown":                HttpEndpoint{Commands: [][]string{{"touchdown", "$x", "$y", "$w", "$h"}}},
	"touchup":                  HttpEndpoint{Commands: [][]string{{"touchup", "$x", "$y", "$w", "$h"}}},
	"touchmove":                HttpEndpoint{Commands: [][]string{{"touchmove", "$x", "$y", "$w", "$h"}}},
	"mouseclick":               HttpEndpoint{Commands: [][]string{{"mouseclick", "$button", "$x", "$y", "$w", "$h"}}},
	"mousedown":                HttpEndpoint{Commands: [][]string{{"mousedown", "$button", "$x", "$y", "$w", "$h"}}},
	"mouseup":                  HttpEndpoint{Commands: [][]string{{"mouseup", "$button", "$x", "$y", "$w", "$h"}}},
	"mousemove":                HttpEndpoint{Commands: [][]string{{"mousemove", "$button", "$x", "$y", "$w", "$h"}}},
	"scrollleft":               HttpEndpoint{Commands: [][]string{{"scrollleft", "$x", "$y", "$w", "$h"}}},
	"scrollright":              HttpEndpoint{Commands: [][]string{{"scrollright", "$x", "$y", "$w", "$h"}}},
	"scrollup":                 HttpEndpoint{Commands: [][]string{{"scrollup", "$x", "$y", "$w", "$h"}}},
	"scrolldown":               HttpEndpoint{Commands: [][]string{{"scrolldown", "$x", "$y", "$w", "$h"}}},
	"openhardkeyboardsettings": HttpEndpoint{Commands: [][]string{{"openhardkeyboardsettings"}}},
	"backorscreenon":           HttpEndpoint{Commands: [][]string{{"backorscreenon"}}},
	"expandnotificationspanel": HttpEndpoint{Commands: [][]string{{"expandnotificationspanel"}}},
	"expandsettingspanel":      HttpEndpoint{Commands: [][]string{{"expandsettingspanel"}}},
	"collapsepanels":           HttpEndpoint{Commands: [][]string{{"collapsepanels"}}},
	"getclipboard":             HttpEndpoint{Commands: [][]string{{"getclipboard"}}},
	"getclipboardcut":          HttpEndpoint{Commands: [][]string{{"getclipboardcut"}}},
	"setclipboard":             HttpEndpoint{Commands: [][]string{{"setclipboard", "$sequence", "$timeout"}}},
	"setclipboardpaste":        HttpEndpoint{Commands: [][]string{{"setclipboardpaste", "$sequence", "$timeout"}}},
	"turnscreenon":             HttpEndpoint{Commands: [][]string{{"turnscreenon"}}},
	"turnscreenoff":            HttpEndpoint{Commands: [][]string{{"turnscreenoff"}}},
	"rotate":                   HttpEndpoint{Commands: [][]string{{"rotate"}}},
	"startapp":                 HttpEndpoint{Commands: [][]string{{"startapp", "$a"}}},
	"resetvideo":               HttpEndpoint{Commands: [][]string{{"resetvideo"}}},
	"senddata":                 HttpEndpoint{Commands: [][]string{{"senddata", "$d"}}},
}
